apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
     app: my-app
     tier: back-end
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        tier: back-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 5
  selector:
    matchLabels:
      tier: back-end